version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - '**/*'
  name: test1-$(date +%Y-%m-%d) 